find_package(Python REQUIRED COMPONENTS Interpreter Development.Module)
find_package(pybind11 CONFIG REQUIRED)

if(NOT DIPTEST_DISABLE_OPENMP)
    message(STATUS "diptest | OpenMP disabled: OFF")
    find_package(OpenMP)
    if ((NOT OpenMP_FOUND) AND APPLE)
        include(SetHomebrew)
        set(OpenMP_ROOT ${HOMEBREW_PREFIX}/opt/libomp)
        find_package(OpenMP)
    endif()
    if (NOT OpenMP_FOUND AND DIPTEST_ENABLE_OPENMP)
        find_package(OpenMP REQUIRED)
    endif()
else()
    set(DIPTEST_ENABLE_OPENMP OFF)
    message(STATUS "diptest | OpenMP disabled: ON")
endif()
